config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/login', to: 'login#index'

  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'

  get '/signin', to: 'signin#new'
  post '/signin', to: 'signin#create'
  delete '/signin', to: 'signin#destroy'
  # delete '/signout', to: 'signin#destroy', as: 'signout'

  resources :restaurants do
    resources :foods do
      resources :comments
    end
  end

  # get "/articles/:id", to: "articles#show"
  # resources :restaurants, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :restaurant
  has_many :comments, dependent: :destroy
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :foods, dependent: :destroy
end

app/models/user.rb
# email:string 
# password_digeset:string
#
#password:string virtual
#password_confirmation:string virtual

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/,message: "Please enter a valid email"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   def create
    @food = Food.find(params[:food_id])
    @comment = @food.comments.create(comment_params)
    redirect_to(restaurant_food_path(@food.restaurant, @food))
  end

  def destroy
    @food = Food.find(params[:food_id])
    @comment = @food.comments.find(params[:id])
    @comment.destroy

    redirect_to restaurant_food_comment_path, notice: "Comment deleted successfully"
  end

  private
    def comment_params
      params.permit(:commenter, :body)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food = @restaurant.foods.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food = @restaurant.foods.find(params[:id])
    @food.destroy
    redirect_to restaurant_food_path, notice: "Food deleted successfully"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find_by(id: session[:current_user_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/restaurants_controller.rb
# app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    @restaurant = Restaurant.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @foods = @restaurant.foods
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to @restaurant
  end

  def edit
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    begin
      puts @restaurant
      @restaurant.destroy
      flash[:notice] = 'Restaurant was successfully destroyed.'
    rescue => e
      flash[:error] = "Error destroying restaurant: #{e.message}"
    end

  puts "After destroy, before redirect"
  puts @restaurant.inspect

    redirect_to restaurants_path, notice: 'Restaurant was successfully deleted.'
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address)
  end


end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def new
    # Render the sign-in form
    @user = User.new
  end

  def index

  end

  def create
    user = User.find_by(email: params[:user][:email])

    if user && user.authenticate(params[:user][:password])
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    # binding.pry
    # Sign out the user
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
    @message = "SignUp Page"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foods/show.html.erb
<h1><%= @food.name %></h1>
<p><%= @food.description %></p>
<p>Price: <%= @food.price %></p>




<h2>Comments</h2>
<% @food.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <%= link_to "Destroy", restaurant_food_comment_path(@restaurant,@food,comment), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

<% end %>

<h2>Add a comment:</h2>
<%= form_with url: restaurant_food_comments_path(@restaurant, @food) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<% if @user %>
  You are logged in as <%= @user.email %>
<% else %>
  You are not logged in
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZomatoClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render partial: 'shared/flash' %>
    
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Add Restaurant</h1>

<%= form_with model: @restaurant do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

  <h1>List of Restaurants</h1>
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-md-4">
      <a href="/restaurants/<%= restaurant.id %>">
        <div class="card mb-3" style="width: 18rem;">
          <img src="/assets/food.jpeg" class="card-img-top" alt="...">
          <div style="display: flex; flex-direction: row;">
            <div class="card-body">
              <h5 class="card-title"><%= restaurant.name %></h5>
              <p class="card-text"><%= restaurant.address %></p>
            </div>


            <%= link_to restaurant_path(restaurant), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } do%>
            <img src="/assets/delete-button.svg" style="margin-top:16px; margin-left:4px;"  height="20px" width="20px" alt="deleteButton">
            <%end%>

              <li><%= link_to "Edit", edit_restaurant_path(restaurant), data: {
                    turbo_method: :edit,
                  } %></li>



            <a href ="/restaurants">
              <img src="/assets/edit.svg" style="margin-top:16px; margin-left:4px;"  height="20px" width="20px" alt="...">
            </a>

          </div>
        </div>
      </a>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <h1><%= @restaurant.name %></h1>
    <h2>Food Items</h2>
    <% @foods.each do |food| %>
      <div class="col-md-4">
        <%= link_to [@restaurant,food] do %>
          <div class="card mb-3" style="width: 18rem;">
            <img src="/assets/food.jpeg" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><strong><%= food.name %></strong></h5>
              <p class="card-text"><%= food.description %></p>
              <p class="card-text"><%= number_to_currency(food.price) %></p>

               <%= link_to [@restaurant,food], data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } do %>

                <img src="/assets/delete-button.svg" style="margin-top:16px; margin-left:4px;"  height="20px" width="20px" alt="deleteButton">
              <%end%>






              <a href ="/restaurants">
               <img src="/assets/edit.svg" style="margin-top:16px; margin-left:4px;"  height="20px" width="20px" alt="...">
              </a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="alert alert-info mt-4 role="alert">
  <%= flash[:notice] %>
</div>
<div class="alert alert-warning mt-4 role="alert">
  <%= flash[:alert] %>
</div>

<div class="alert alert-success mt-4 role="alert">
  <%= flash[:success]%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= image_tag "logo.png", class: "navbar-brand",width: "40", height: "50" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active', 'aria-content'=>'page'%>
        </li>
        <li class="nav-item">
          <%= link_to restaurants_path, class: 'nav-link' do%>
            Add Restraunt
          <%end%>
        </li>
        <li class="nav-item">
            <% if session[:current_user_id] %>
            
            <li><%= link_to "Sign out", signin_path, data: {
              turbo_method: :delete,
            }, class: 'btn btn-primary' %></li>
            <%else%>
              <%= link_to signin_path, class:"btn btn-primary" do%>
                Sign in
              <% end %>
            <%end%>
        </li>
        <% if !session[:current_user_id]%>
          <li class="nav-item" style="margin-left: 10px;">
            <%= link_to signup_path, class: 'btn btn-primary' do%>
              SignUp
            <%end%>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/signin/new.html.erb
<h2>Sign In</h2>

<%= form_with(model: @user, url: '/signin', method: 'post') do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit 'Sign In' %>
  </div>
<% end %>